name: Add issue ao Project v2 (projeto-teste)

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: read # 'projects' não é suportado aqui; usaremos GH_PAT nos passos

jobs:
  add:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'Solicitacao') # ajuste se o label do template for outro
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }} # PAT com acesso a Projects v2 da organização
      ORG: Ljaning
      PROJECT_TITLE: projeto-teste
      ISSUE_NODE: ${{ github.event.issue.node_id }}
    steps:
      - name: Resolver IDs do projeto e adicionar item
        run: |
          set -e

          # 1) Localiza o projeto da organização pelo título
          gh api graphql -f query='
            query($org:String!){
              organization(login:$org){
                projectsV2(first:100){
                  nodes{ id title }
                }
              }
            }' -f org="$ORG" > proj.json

          PROJECT_ID=$(jq -r --arg t "$PROJECT_TITLE" '.data.organization.projectsV2.nodes[] | select(.title==$t) | .id' proj.json)
          [ -n "$PROJECT_ID" ] || { echo "Projeto \"$PROJECT_TITLE\" não encontrado na org $ORG"; exit 1; }

          # 2) Adiciona a issue como item do Project v2
          gh api graphql -f query='
            mutation($pid:ID!, $cid:ID!){
              addProjectV2ItemById(input:{projectId:$pid, contentId:$cid}){
                item { id }
              }
            }' -f pid="$PROJECT_ID" -f cid="$ISSUE_NODE" > add.json

          ITEM_ID=$(jq -r '.data.addProjectV2ItemById.item.id' add.json)
          [ -n "$ITEM_ID" ] || { echo "Falha ao adicionar item ao projeto"; exit 1; }

          # 3) Busca campo Status e a opção "Triage"
          gh api graphql -f query='
            query($pid:ID!){
              node(id:$pid){
                ... on ProjectV2{
                  fields(first:100){
                    nodes{
                      ... on ProjectV2SingleSelectField{
                        id name
                        options{ id name }
                      }
                    }
                  }
                }
              }
            }' -f pid="$PROJECT_ID" > fields.json

          STATUS_FIELD_ID=$(jq -r '.data.node.fields.nodes[] | select(.name=="Status") | .id' fields.json)
          TRIAGE_OPT=$(jq -r '.data.node.fields.nodes[] | select(.name=="Status") | .options[] | select(.name=="Triage") | .id' fields.json)
          [ -n "$STATUS_FIELD_ID" ] && [ -n "$TRIAGE_OPT" ] || { echo "Campo Status e/ou opção Triage não encontrados"; exit 1; }

          # 4) Seta Status = Triage para o item
          #    >>>> ALTERAÇÃO: $opt agora é String! (não ID!)
          gh api graphql -f query='
            mutation($project:ID!, $item:ID!, $field:ID!, $opt:String!){
              updateProjectV2ItemFieldValue(input:{
                projectId:$project,
                itemId:$item,
                fieldId:$field,
                value:{ singleSelectOptionId:$opt }
              }){
                clientMutationId
              }
            }' -f project="$PROJECT_ID" -f item="$ITEM_ID" -f field="$STATUS_FIELD_ID" -f opt="$TRIAGE_OPT" >/dev/null

          echo "Item adicionado ao projeto \"$PROJECT_TITLE\" e movido para Status=Triage."
